// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXjaooShkbm88cvJKJVMaA_f-4NaBjB9E',
    appId: '1:450429861696:web:45ea3f33e579c1e49ec4a5',
    messagingSenderId: '450429861696',
    projectId: 'flutter-85c9e',
    authDomain: 'flutter-85c9e.firebaseapp.com',
    storageBucket: 'flutter-85c9e.appspot.com',
    measurementId: 'G-3T846ZP9R5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU4PirSx4sRYnBpH8bb1XLEQsYJPoYFxs',
    appId: '1:450429861696:android:5fe84aeb5b97b5599ec4a5',
    messagingSenderId: '450429861696',
    projectId: 'flutter-85c9e',
    storageBucket: 'flutter-85c9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOJxdAqsvvMn92boWvqsKireL7Aj-Q96s',
    appId: '1:450429861696:ios:b005549ded0567309ec4a5',
    messagingSenderId: '450429861696',
    projectId: 'flutter-85c9e',
    storageBucket: 'flutter-85c9e.appspot.com',
    iosClientId: '450429861696-173hvliel5p1k28cltl4iiactb3h9hal.apps.googleusercontent.com',
    iosBundleId: 'com.example.cvversion2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOJxdAqsvvMn92boWvqsKireL7Aj-Q96s',
    appId: '1:450429861696:ios:b005549ded0567309ec4a5',
    messagingSenderId: '450429861696',
    projectId: 'flutter-85c9e',
    storageBucket: 'flutter-85c9e.appspot.com',
    iosClientId: '450429861696-173hvliel5p1k28cltl4iiactb3h9hal.apps.googleusercontent.com',
    iosBundleId: 'com.example.cvversion2',
  );
}
